const seed={owners:[{id:'o1',name:'Manuel Marsio'},{id:'o2',name:'Famiglia Marsio'}],properties:[{id:'p1',name:'Via Torti',city:'Genova',type:'Appartamento',ownerId:'o1',value:145000,rent:650,status:'Locato'},{id:'p2',name:'Via San Martino',city:'Genova',type:'Appartamento',ownerId:'o2',value:105000,rent:350,status:'Locato'},{id:'p3',name:'Via Servettaz',city:'Savona',type:'Bilocale',ownerId:'o1',value:50000,rent:370,status:'Locato'}],movements:[{id:'m1',date:new Date().toISOString().slice(0,10),propertyId:'p1',description:'Canone mensile',type:'Entrata',amount:650}],deadlines:[{id:'d1',date:new Date(Date.now()+864e5*7).toISOString().slice(0,10),propertyId:'p1',title:'Pagamento condominio',category:'Condominio'},{id:'d2',date:new Date(Date.now()+864e5*19).toISOString().slice(0,10),propertyId:'p3',title:'Verifica contratto',category:'Contratto'}]};
let db=JSON.parse(localStorage.getItem('gi-data')||'null')||seed;let activeModal='property';
const euro=n=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(Number(n)||0);const $=s=>document.querySelector(s);const save=()=>{localStorage.setItem('gi-data',JSON.stringify(db));render()};const owner=id=>db.owners.find(x=>x.id===id)?.name||'Non assegnato';const property=id=>db.properties.find(x=>x.id===id)?.name||'—';
function render(){const annual=db.properties.reduce((s,p)=>s+Number(p.rent||0)*12,0),value=db.properties.reduce((s,p)=>s+Number(p.value||0),0),expenses=db.movements.filter(m=>m.type==='Uscita').reduce((s,m)=>s+Number(m.amount),0);$('#kpis').innerHTML=[['Valore patrimonio',euro(value),'Valore indicativo'],['Canoni annuali',euro(annual),'Rendita lorda'],['Immobili',db.properties.length,'Unità censite'],['Uscite registrate',euro(expenses),'Totale movimenti']].map(x=>`<div class="kpi"><small>${x[0]}</small><strong>${x[1]}</strong><span>${x[2]}</span></div>`).join('');
const propRows=db.properties.slice(0,4).map(p=>`<div class="property-row"><span class="property-icon">⌂</span><div class="row-main"><strong>${p.name}</strong><small>${p.city} · ${owner(p.ownerId)}</small></div><span class="money">${euro(p.rent)}/m</span></div>`).join('');$('#propertyPreview').innerHTML=propRows||'<div class="empty">Nessun immobile inserito</div>';
const sorted=[...db.deadlines].sort((a,b)=>a.date.localeCompare(b.date));$('#deadlinePreview').innerHTML=sorted.slice(0,4).map(deadlineRow).join('')||'<div class="empty">Nessuna scadenza</div>';$('#deadlineList').innerHTML=sorted.map(deadlineRow).join('')||'<div class="empty">Nessuna scadenza</div>';
const filter=$('#ownerFilter').value;$('#ownerFilter').innerHTML='<option value="">Tutti i proprietari</option>'+db.owners.map(o=>`<option value="${o.id}" ${filter===o.id?'selected':''}>${o.name}</option>`).join('');
$('#propertyGrid').innerHTML=db.properties.filter(p=>!filter||p.ownerId===filter).map(p=>`<article class="property-card"><div class="property-cover"><span>${p.status}</span></div><div class="card-body"><h3>${p.name}</h3><p>${p.type} · ${p.city}<br>${owner(p.ownerId)}</p><div class="card-stats"><div><small>VALORE</small><strong>${euro(p.value)}</strong></div><div><small>CANONE</small><strong>${euro(p.rent)}/m</strong></div></div></div></article>`).join('')||'<div class="empty">Nessun immobile</div>';
$('#ownerGrid').innerHTML=db.owners.map(o=>{const ps=db.properties.filter(p=>p.ownerId===o.id);return`<article class="owner-card"><div class="owner-head"><span class="avatar">${o.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><strong>${o.name}</strong><div>${ps.length} immobili</div></div></div><div class="card-stats"><div><small>PATRIMONIO</small><strong>${euro(ps.reduce((s,p)=>s+Number(p.value),0))}</strong></div><div><small>CANONI/MESE</small><strong>${euro(ps.reduce((s,p)=>s+Number(p.rent),0))}</strong></div></div></article>`}).join('');
$('#movementRows').innerHTML=[...db.movements].sort((a,b)=>b.date.localeCompare(a.date)).map(m=>`<tr><td>${formatDate(m.date)}</td><td>${property(m.propertyId)}</td><td>${m.description}</td><td><span class="tag ${m.type==='Entrata'?'in':'out'}">${m.type}</span></td><td class="money">${m.type==='Uscita'?'-':'+'}${euro(m.amount)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nessun movimento</td></tr>'}
function deadlineRow(d){const date=new Date(d.date+'T12:00:00');return`<div class="deadline-row"><div class="date-box"><strong>${date.getDate()}</strong><small>${date.toLocaleDateString('it-IT',{month:'short'}).toUpperCase()}</small></div><div class="row-main"><strong>${d.title}</strong><small>${property(d.propertyId)} · ${d.category}</small></div></div>`}function formatDate(d){return new Date(d+'T12:00:00').toLocaleDateString('it-IT')}
const configs={property:{title:'Nuovo immobile',fields:[['name','Nome immobile','text'],['city','Città','text'],['type','Tipologia','text'],['ownerId','Proprietario','owner'],['value','Valore stimato','number'],['rent','Canone mensile','number'],['status','Stato','status']]},owner:{title:'Nuovo proprietario',fields:[['name','Nome e cognome','text']]},movement:{title:'Nuovo movimento',fields:[['date','Data','date'],['propertyId','Immobile','property'],['description','Descrizione','text'],['type','Tipo','movement'],['amount','Importo','number']]},deadline:{title:'Nuova scadenza',fields:[['date','Data','date'],['propertyId','Immobile','property'],['title','Titolo','text'],['category','Categoria','text']]}};
function openModal(type){activeModal=type;const c=configs[type];$('#modalTitle').textContent=c.title;$('#formFields').innerHTML=c.fields.map(([name,label,type])=>field(name,label,type)).join('');$('#modal').showModal()}function field(name,label,type){let input;if(type==='owner')input=`<select name="${name}" required>${db.owners.map(o=>`<option value="${o.id}">${o.name}</option>`)}</select>`;else if(type==='property')input=`<select name="${name}" required>${db.properties.map(p=>`<option value="${p.id}">${p.name}</option>`)}</select>`;else if(type==='status')input=`<select name="${name}"><option>Locato</option><option>Libero</option><option>In manutenzione</option></select>`;else if(type==='movement')input=`<select name="${name}"><option>Entrata</option><option>Uscita</option></select>`;else input=`<input name="${name}" type="${type}" ${type==='number'?'min="0" step="0.01"':''} ${type==='date'?`value="${new Date().toISOString().slice(0,10)}"`:''} required>`;return`<label class="field"><span>${label}</span>${input}</label>`}
$('#entityForm').addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.id=crypto.randomUUID();if(activeModal==='property')db.properties.push(data);else if(activeModal==='owner')db.owners.push(data);else if(activeModal==='movement')db.movements.push(data);else db.deadlines.push(data);$('#modal').close();save();toast('Salvato correttamente')});
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view],[data-go]');if(nav){show(nav.dataset.view||nav.dataset.go)}const modal=e.target.closest('[data-modal]');if(modal)openModal(modal.dataset.modal)});$('#primaryAction').onclick=()=>openModal('property');$('#ownerFilter').onchange=render;$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');
function show(id){document.querySelectorAll('.view,.nav-item').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');document.querySelector(`[data-view="${id}"]`).classList.add('active');$('#pageTitle').textContent=document.querySelector(`[data-view="${id}"] span`).textContent;$('.sidebar').classList.remove('open')}function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
$('#currentMonth').textContent=new Date().toLocaleDateString('it-IT',{month:'long',year:'numeric'});render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');
