import { Pencil, Trash2, Check } from 'lucide-react';

const typeStyle = { condominio: 'bg-blue-50 text-blue-700 dark:bg-blue-950 dark:text-blue-400', straordinaria: 'bg-purple-50 text-purple-700 dark:bg-purple-950 dark:text-purple-400', intervento_futuro: 'bg-amber-50 text-amber-700 dark:bg-amber-950 dark:text-amber-400', tassa: 'bg-rose-50 text-rose-700 dark:bg-rose-950 dark:text-rose-400', manutenzione: 'bg-teal-50 text-teal-700 dark:bg-teal-950 dark:text-teal-400', altro: 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-400' };
const typeLabel = { condominio: 'Condominio', straordinaria: 'Straordinaria', intervento_futuro: 'Intervento futuro', tassa: 'Tassa', manutenzione: 'Manutenzione', altro: 'Altro' };

export default function ExpenseCard({ expense, onEdit, onDelete, onToggleStatus }) {
  return <article className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-4 shadow-sm">
    <div className="flex items-start justify-between gap-3">
      <div className="flex-1"><div className="flex flex-wrap items-center gap-2"><span className={`rounded-lg px-2.5 py-0.5 text-xs font-semibold ${typeStyle[expense.type]}`}>{typeLabel[expense.type]}</span>{expense.recurring && <span className="rounded-lg bg-slate-100 dark:bg-slate-800 px-2 py-0.5 text-xs font-semibold text-slate-500 dark:text-slate-400">{expense.frequency}</span>}{expense.installment_total > 1 && <span className="rounded-lg bg-indigo-50 dark:bg-indigo-950 px-2 py-0.5 text-xs font-semibold text-indigo-700 dark:text-indigo-400">Rata {expense.installment_number}/{expense.installment_total}</span>}{expense.property_name && <span className="text-xs text-slate-400 dark:text-slate-500">· {expense.property_name}</span>}</div><p className="mt-2 font-semibold text-slate-900 dark:text-slate-100">{expense.description}</p><p className="mt-0.5 text-xs text-slate-500 dark:text-slate-400">{new Date(expense.date).toLocaleDateString('it-IT', { day: 'numeric', month: 'short', year: 'numeric' })}</p></div>
      <p className="text-lg font-bold text-slate-900 dark:text-slate-100">€ {(expense.amount || 0).toLocaleString('it-IT')}</p>
    </div>
    <div className="mt-3 flex items-center gap-2 border-t border-slate-100 dark:border-slate-800 pt-3">
      <button onClick={() => onToggleStatus(expense)} className={`flex items-center gap-1.5 rounded-lg px-2.5 py-1.5 text-xs font-semibold ${expense.status === 'pagata' ? 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900 dark:text-emerald-400' : 'bg-slate-100 text-slate-500 dark:bg-slate-800 dark:text-slate-400'}`}><Check size={14} /> {expense.status === 'pagata' ? 'Pagata' : 'Da pagare'}</button>
      <div className="ml-auto flex gap-1.5"><button onClick={() => onEdit(expense)} className="rounded-lg bg-slate-100 dark:bg-slate-800 p-2 text-slate-500 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700"><Pencil size={15} /></button><button onClick={() => onDelete(expense)} className="rounded-lg bg-slate-100 dark:bg-slate-800 p-2 text-slate-500 dark:text-slate-400 hover:bg-rose-50 dark:hover:bg-rose-950 hover:text-rose-600 dark:hover:text-rose-400"><Trash2 size={15} /></button></div>
    </div>
  </article>;
}