import { useEffect, useMemo, useState } from 'react';
import { Plus, Wallet, Download } from 'lucide-react';
import { addMonths } from 'date-fns';
import { exportToCsv } from '@/utils/exportCsv';
import { base44 } from '@/api/base44Client';
import { useConfirm } from '@/components/ConfirmProvider';
import { toast } from '@/components/ui/use-toast';
import { useModalParam } from '@/hooks/useModalParam';
import StyledSelect from '@/components/StyledSelect';
import StickyFilters from '@/components/StickyFilters';
import AppShell from '@/components/AppShell';
import PullRefresh from '@/components/PullRefresh';
import ExpenseCard from '@/components/expenses/ExpenseCard';
import ExpenseForm from '@/components/expenses/ExpenseForm';

export default function Expenses() {
  const confirm = useConfirm();
  const [expenses, setExpenses] = useState([]), [properties, setProperties] = useState([]), [owners, setOwners] = useState([]), [loading, setLoading] = useState(true);
  const { isOpen: formOpen, open: openForm, close: closeForm } = useModalParam('expense-form');
  const [editing, setEditing] = useState(null), [saving, setSaving] = useState(false), [filter, setFilter] = useState('all'), [ownerFilter, setOwnerFilter] = useState('all');
  const load = () => Promise.all([base44.entities.Expense.list('-date', 200), base44.entities.Property.list('-created_date'), base44.entities.Owner.list('-created_date')]).then(([e, p, o]) => { setExpenses(e); setProperties(p); setOwners(o); }).finally(() => setLoading(false));
  useEffect(() => { load(); }, []);
  const propName = (id) => properties.find((p) => p.id === id)?.name || '';
  const ownerMap = useMemo(() => Object.fromEntries(properties.map((p) => [p.id, p.owner_id])), [properties]);
  const visible = useMemo(() => expenses.filter((e) => (filter === 'all' || e.type === filter) && (ownerFilter === 'all' || ownerMap[e.property_id] === ownerFilter)), [expenses, filter, ownerFilter, ownerMap]);
  const save = async (e) => { e.preventDefault(); setSaving(true); const data = Object.fromEntries(new FormData(e.currentTarget)); data.amount = Number(data.amount); data.recurring = data.recurring === 'on'; data.property_name = propName(data.property_id); const isSplit = data.split_installments === 'on'; delete data.split_installments; const installmentsCount = Number(data.installments_count) || 1; delete data.installments_count; if (!editing?.id && data.type === 'condominio' && isSplit && installmentsCount > 1) { const perInstallment = Math.round((data.amount / installmentsCount) * 100) / 100; const startDate = new Date(data.date); const intervalMonths = 12 / installmentsCount; const records = []; for (let i = 0; i < installmentsCount; i++) { const d = addMonths(startDate, i * intervalMonths); records.push({ ...data, amount: perInstallment, date: d.toISOString().slice(0, 10), installment_number: i + 1, installment_total: installmentsCount, description: data.description + ' — Rata ' + (i + 1) + '/' + installmentsCount }); } const prev = expenses; const tempIds = records.map(() => 'temp-' + Date.now() + '-' + Math.random()); setExpenses([...records.map((r, i) => ({ ...r, id: tempIds[i] })), ...expenses]); try { const created = await base44.entities.Expense.bulkCreate(records); setExpenses((p) => [...created, ...p.filter((x) => !tempIds.includes(x.id))]); closeForm(); } catch { setExpenses(prev); toast({ variant: 'destructive', title: 'Errore', description: 'Creazione rate non riuscita' }); } setSaving(false); return; } const prev = expenses; if (editing?.id) { setExpenses(expenses.map((x) => x.id === editing.id ? { ...x, ...data } : x)); try { await base44.entities.Expense.update(editing.id, data); closeForm(); } catch { setExpenses(prev); toast({ variant: 'destructive', title: 'Errore', description: 'Aggiornamento non riuscito' }); } } else { const tempId = 'temp-' + Date.now(); setExpenses([{ ...data, id: tempId }, ...expenses]); try { const created = await base44.entities.Expense.create(data); setExpenses((p) => [created, ...p.filter((x) => x.id !== tempId)]); closeForm(); } catch { setExpenses(prev); toast({ variant: 'destructive', title: 'Errore', description: 'Creazione non riuscita' }); } } setSaving(false); };
  const remove = async (exp) => { if (!await confirm({ title: 'Elimina spesa', description: `Eliminare "${exp.description}"?`, destructive: true, confirmLabel: 'Elimina' })) return; const prev = expenses; setExpenses(expenses.filter((x) => x.id !== exp.id)); try { await base44.entities.Expense.delete(exp.id); } catch { setExpenses(prev); toast({ variant: 'destructive', title: 'Errore', description: 'Eliminazione non riuscita' }); } };
  const toggleStatus = async (exp) => { const newStatus = exp.status === 'pagata' ? 'da_pagare' : 'pagata'; setExpenses(prev => prev.map(x => x.id === exp.id ? { ...x, status: newStatus } : x)); await base44.entities.Expense.update(exp.id, { status: newStatus }); };
  const typeLabel = { condominio: 'Condominio', straordinaria: 'Straordinaria', intervento_futuro: 'Intervento futuro', tassa: 'Tassa', manutenzione: 'Manutenzione', altro: 'Altro' };
  const freqLabel = { mensile: 'Mensile', trimestrale: 'Trimestrale', annuale: 'Annuale', una_tantum: 'Una tantum' };
  const handleExport = () => {
    const rows = visible.map((e) => ({ immobile: e.property_name || '', tipo: typeLabel[e.type] || e.type || '', descrizione: e.description || '', importo: (e.amount || 0).toFixed(2).replace('.', ','), data: e.date ? e.date.split('-').reverse().join('/') : '', ricorrente: e.recurring ? 'Sì' : 'No', frequenza: e.recurring ? (freqLabel[e.frequency] || '') : '', stato: e.status === 'pagata' ? 'Pagata' : 'Da pagare' }));
    exportToCsv('spese-' + new Date().toISOString().slice(0, 10) + '.csv', rows, [{ key: 'immobile', label: 'Immobile' }, { key: 'tipo', label: 'Tipo' }, { key: 'descrizione', label: 'Descrizione' }, { key: 'importo', label: 'Importo (€)' }, { key: 'data', label: 'Data' }, { key: 'ricorrente', label: 'Ricorrente' }, { key: 'frequenza', label: 'Frequenza' }, { key: 'stato', label: 'Stato' }]);
  };
  const filters = ['all', 'condominio', 'straordinaria', 'intervento_futuro', 'tassa', 'manutenzione', 'altro'];
  const filterLabel = { all: 'Tutte', condominio: 'Condominio', straordinaria: 'Straordinaria', intervento_futuro: 'Interventi futuri', tassa: 'Tasse', manutenzione: 'Manutenzione', altro: 'Altro' };
  return <AppShell>
    <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-teal-700 dark:text-teal-400">Gestione</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Spese e interventi</h1></div><div className="flex gap-3"><button onClick={handleExport} disabled={visible.length === 0} className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 px-5 py-3 font-semibold text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-700 disabled:opacity-50"><Download size={18} /> Esporta CSV</button><button onClick={() => { setEditing(null); openForm(); }} className="flex items-center justify-center gap-2 rounded-xl bg-slate-900 dark:bg-slate-100 px-5 py-3 font-semibold text-white dark:text-slate-900 hover:bg-slate-800 dark:hover:bg-slate-200"><Plus size={18} /> Aggiungi spesa</button></div></div>
    <StickyFilters><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><StyledSelect value={ownerFilter} onChange={setOwnerFilter} placeholder="Tutti i proprietari" options={[{ value: 'all', label: 'Tutti i proprietari' }, ...owners.map((o) => ({ value: o.id, label: o.name }))]} /><div className="flex flex-wrap gap-2">{filters.map((f) => <button key={f} onClick={() => setFilter(f)} className={`rounded-full px-4 py-1.5 text-sm font-semibold ${filter === f ? 'bg-slate-900 text-white dark:bg-slate-100 dark:text-slate-900' : 'bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-400 border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-700'}`}>{filterLabel[f]}</button>)}</div></div></StickyFilters>
    {loading ? <div className="py-16 text-center text-slate-500 dark:text-slate-400">Caricamento…</div> : visible.length ? <PullRefresh onRefresh={load}><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((exp) => <ExpenseCard key={exp.id} expense={exp} onEdit={(x) => { setEditing(x); openForm(); }} onDelete={remove} onToggleStatus={toggleStatus} />)}</div></PullRefresh> : <div className="mt-5 rounded-2xl border border-dashed border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 py-16 text-center"><Wallet size={32} className="mx-auto text-slate-300 dark:text-slate-600" /><p className="mt-3 font-semibold text-slate-800 dark:text-slate-200">Nessuna spesa</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Registra condominio, tasse o interventi.</p></div>}
    <ExpenseForm isOpen={formOpen} expense={editing || {}} properties={properties} onSubmit={save} onClose={closeForm} saving={saving} />
  </AppShell>;
}