const rentLabel = { libero: 'Libero', concordato: 'Concordato', scrittura_privata: 'Scrittura privata' };

export default function TaxBreakdown({ properties }) {
  if (!properties.length) return <p className="text-sm text-slate-500 dark:text-slate-400">Nessun immobile da analizzare.</p>;
  return <>
    {/* Mobile cards */}
    <div className="space-y-3 sm:hidden">
      {properties.map((p) => { const pct = (p.ownership_percentage || 100) / 100; const monthlyTax = (p.monthly_rent || 0) * (p.tax_rate || 0) / 100 * pct; return <div key={p.id} className="rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-4"><div className="flex items-start justify-between gap-2"><p className="font-semibold text-slate-900 dark:text-slate-100">{p.name}</p><span className="rounded-lg bg-slate-100 dark:bg-slate-800 px-2 py-0.5 text-xs font-semibold text-slate-600 dark:text-slate-400">{rentLabel[p.rent_type]}</span></div><div className="mt-3 grid grid-cols-2 gap-2 text-sm"><div><p className="text-xs text-slate-500 dark:text-slate-400">Quota cond.</p><p className="text-slate-600 dark:text-slate-400">€ {(p.condo_fee || 0).toLocaleString('it-IT')}</p></div><div><p className="text-xs text-slate-500 dark:text-slate-400">% proprietà</p><p className="text-slate-600 dark:text-slate-400">{p.ownership_percentage || 100}%</p></div><div><p className="text-xs text-slate-500 dark:text-slate-400">Aliquota</p><p className="text-slate-600 dark:text-slate-400">{p.tax_rate}%</p></div><div><p className="text-xs text-slate-500 dark:text-slate-400">Tasse /mese</p><p className="text-rose-600 dark:text-rose-400">€ {monthlyTax.toLocaleString('it-IT')}</p></div></div><div className="mt-2 border-t border-slate-100 dark:border-slate-800 pt-2 text-right"><span className="text-xs text-slate-500 dark:text-slate-400">Tasse /anno: </span><span className="font-semibold text-rose-600 dark:text-rose-400">€ {(monthlyTax * 12).toLocaleString('it-IT')}</span></div></div>; })}
    </div>
    {/* Desktop table */}
    <div className="hidden overflow-x-auto sm:block"><table className="w-full min-w-[640px] text-sm"><thead><tr className="border-b border-slate-200 dark:border-slate-800 text-left text-xs uppercase tracking-wider text-slate-500 dark:text-slate-400"><th className="pb-3 pr-4 font-semibold">Immobile</th><th className="pb-3 pr-4 font-semibold">Canone</th><th className="pb-3 pr-4 font-semibold">Quota cond.</th><th className="pb-3 pr-4 font-semibold">% proprietà</th><th className="pb-3 pr-4 font-semibold">Aliquota</th><th className="pb-3 pr-4 font-semibold">Tasse /mese</th><th className="pb-3 pr-4 font-semibold">Tasse /anno</th></tr></thead><tbody>{properties.map((p) => { const pct = (p.ownership_percentage || 100) / 100; const monthlyTax = (p.monthly_rent || 0) * (p.tax_rate || 0) / 100 * pct; return <tr key={p.id} className="border-b border-slate-100 dark:border-slate-800"><td className="py-3 pr-4 font-semibold text-slate-900 dark:text-slate-100">{p.name}</td><td className="py-3 pr-4"><span className="rounded-lg bg-slate-100 dark:bg-slate-800 px-2 py-0.5 text-xs font-semibold text-slate-600 dark:text-slate-400">{rentLabel[p.rent_type]}</span></td><td className="py-3 pr-4 text-slate-500 dark:text-slate-400">€ {(p.condo_fee || 0).toLocaleString('it-IT')}</td><td className="py-3 pr-4 text-slate-500 dark:text-slate-400">{p.ownership_percentage || 100}%</td><td className="py-3 pr-4 text-slate-600 dark:text-slate-400">{p.tax_rate}%</td><td className="py-3 pr-4 text-rose-600 dark:text-rose-400">€ {monthlyTax.toLocaleString('it-IT')}</td><td className="py-3 pr-4 font-semibold text-rose-600 dark:text-rose-400">€ {(monthlyTax * 12).toLocaleString('it-IT')}</td></tr>; })}</tbody></table></div>
    <p className="mt-3 text-xs text-slate-400 dark:text-slate-500">La quota condominiale è un rimborso spese e non concorre al reddito tassabile.</p>
  </>;
}